-- ...\esx_policejob\locales/en.lua
Locales['en'] = {
  -- Cloackroom
  ['cloakroom'] = 'Omklädningsrum',
  ['citizen_wear'] = 'Civil klädsel',
  ['police_wear'] = 'Polisuniform',
  ['sheriff_wear'] = 'Länsmansuniform',
  ['lieutenant_wear'] = 'NFC outfit ',
  ['lieutenant_wear2'] = 'Sandy klädsel 1 ',
  ['lieutenant_wear3'] = 'Sandy klädsel 2 ',
  ['commandant_wear'] = 'FBI uniform',
  ['statepd_wear'] = 'Landspolis uniform',
  ['specops_wear'] = 'Specialstyrkans uniform',
  ['open_cloackroom'] = 'Tryck ~INPUT_CONTEXT~ för att byta om',
  -- Armory
  ['get_weapon'] = 'Ta vapen',
  ['put_weapon'] = 'Lägg bort vapen',
  ['buy_weapons'] = 'Köp vapen',
  ['armory'] = 'Arsenal',
  ['open_armory'] = 'Tryck ~INPUT_CONTEXT~ för att komma åt arsenalen',
  -- Vehicles
  ['vehicle_menu'] = 'Fordon',
  ['vehicle_out'] = 'Det är redan ett fordon ute',
  ['vehicle_spawner'] = 'Tryck ~INPUT_CONTEXT~ för att ta ut ett fordon',
  ['store_vehicle'] = 'Tryck ~INPUT_CONTEXT~ för att ställa in ett fordon',
  ['service_max'] = 'Max antal poliser i tjänst: ',
  -- Action Menu
  ['citizen_interaction'] = 'Interaktion med medborgare',
  ['vehicle_interaction'] = 'Interaktion med fordon',
  ['object_spawner'] = 'Ta fram objekt',
  ['animations'] = 'Aktiviteter',

  ['id_card'] = 'iD kort',
  ['search'] = 'Genomsök',
  ['handcuff'] = 'Handfängsla',
  ['drag'] = 'Dra',
  ['put_in_vehicle'] = 'Sätt i fordon',
  ['out_the_vehicle'] = 'Ta ut ur fordon',
  ['fine'] = 'Böter',
  ['license_check'] = 'hantera licens',
  ['license_revoke'] = 'återkalla licens',
  ['license_revoked'] = 'ditt ~b~%s~s~ har blivit ~y~indraget~s~!', 
  ['licence_you_revoked'] = 'du klippte ~b~%s~s~ på plats, som tillhörde ~y~%s~s~', 
  ['no_players_nearby'] = 'no players nearby',

  ['vehicle_info'] = 'vehicle Info',
  ['pick_lock'] = 'lockpick Vehicle',
  ['vehicle_unlocked'] = 'vehicle ~g~Unlocked~s~',
  ['no_vehicles_nearby'] = 'no vehicles nearby',
  ['traffic_interaction'] = 'Interaction Voirie',
  ['cone'] = 'cone',
  ['barrier'] = 'barrier',
  ['spikestrips'] = 'spikestrips',
  ['box'] = 'box',
  ['cash'] = 'Box of cash',
  ['police_animations'] = 'Police Animations',
  ['dotraffic'] = 'Do a traffic stop',
  ['take_note'] = 'Take notes',
  ['stand_by'] = 'Stand by',
  ['stand_by_2'] = 'Stand by 2',
  ['stand_by_3'] = 'Stand by 3',
  ['crowd_control'] = 'Crowd control',
  ['doinvestigate'] = 'Investigate',
  ['dobinoculars'] = 'Use the binoculars',
  ['taking_notes'] = 'Im done with taking notes',
  ['dealing_with_traffic'] = 'Dealing with traffic is hard',
  ['standing_cop'] = 'I cant be here anymore',
  ['standing_cop_2'] = 'I cant be here anymore',
  ['standing_cop_3'] = 'I cant be here anymore',
  ['use_binoculars'] = 'I cant see nothing',
  ['do_crowd_control'] = 'The crowd is contained',
  ['investigate_done'] = 'My investigation is done',
  ['docrouch'] = 'Crouch',
  ['kneel'] = 'Let me get up',
  ['hang_out'] = 'Free time 1',
  ['hanging_out'] = 'Lets go work',
  ['doleaning'] = 'Free time 2',
  ['dosmoking'] = 'Free time 3',
  ['dodrinking'] = 'Free time 4',
  ['domobile'] = 'Free time 5',
  ['aacoffe'] = 'Morning coffe',
  ['push_ups'] = 'Exercise a little',
  ['exercise'] = 'Im tired',
  ['cancel_emote'] = 'Cancel animation',
  ['emotecanceled'] = 'Animation stoped',
  -- ID Card Menu
  ['name'] = 'name : ',
  ['bac'] = 'bAC : ',
  -- Body Search Menu
  ['confiscate_dirty'] = 'confiscate dirty money: $',
  ['guns_label'] = '--- Guns ---',
  ['confiscate'] = 'confiscate ',
  ['inventory_label'] = '--- Inventory ---',
  ['confiscate_inv'] = 'confiscate x',

  ['traffic_offense'] = 'traffic Offense',
  ['minor_offense'] = 'minor Offense',
  ['average_offense'] = 'average Offense',
  ['major_offense'] = 'major Offense',
  ['fine_total'] = 'fine: ',
  -- Vehicle Info Menu
  ['plate'] = 'Plate: ',
  ['owner_unknown'] = 'owner: Unknown',
  ['owner'] = 'owner: ',
  -- Weapons Menus
  ['get_weapon_menu'] = 'armory - Take Weapon',
  ['put_weapon_menu'] = 'armory - Put Weapon',
  ['buy_weapon_menu'] = 'armory - Buy Guns',
  ['not_enough_money'] = 'you do not have enough money',
  -- Boss Menu
  ['take_company_money'] = 'withdraw Company Money',
  ['deposit_money'] = 'deposit Money',
  ['amount_of_withdrawal'] = 'amount of Withdrawal',
  ['invalid_amount'] = 'amount Invalid',
  ['amount_of_deposit'] = 'amount of Deposit',
  ['open_bossmenu'] = 'press ~INPUT_CONTEXT~ to open the menu',
  ['quantity_invalid'] = 'invalid quantity',
  ['have_withdraw'] = 'you have withdrawn x',
  ['added'] = 'you added x',
  ['quantity'] = 'quantity',
  ['inventory'] = 'inventory',
  ['police_stock'] = 'Police Stock',
  -- Misc
  ['remove_object'] = 'press ~INPUT_CONTEXT~ to delete the object',
  ['map_blip'] = 'police Station',
  -- Notifications
  ['from'] = '~s~ from ~b~',
  ['you_have_confinv'] = 'you have confiscated ~y~x',
  ['confinv'] = '~s~ confiscated from you ~y~x',
  ['you_have_confdm'] = 'you have confiscated ~y~$',
  ['confdm'] = '~s~ confiscated from you ~y~$',
  ['you_have_confweapon'] = 'you have confiscated ~y~x1 ',
  ['confweapon'] = '~s~ confiscated from you ~y~x1 ',
  ['alert_police'] = 'alert police',
  -- Authorized Vehicles
  ['police'] = 'patrol Vehicle 1',
  ['police2'] = 'patrol Vehicle 2',
  ['police3'] = 'patrol Vehicle 3',
  ['police4'] = 'unmarked Vehicle',
  ['policeb'] = 'motorcycle',
  ['policet'] = 'transport Van',
  ['fbi'] = 'Unmarked Car',
  ['fbi2'] = 'Unmarked Van',
  ['pranger'] = 'Tull Car',
  --['polf430'] = 'pursuit car',
}
